name: Ventoy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: centos:7

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: yum install -y \
        libXpm net-tools bzip2 wget vim gcc gcc-c++ samba dos2unix glibc-devel glibc.i686 glibc-devel.i686 \
        mpfr.i686 mpfr-devel.i686 zlib.i686 rsync autogen autoconf automake libtool gettext* bison binutils \
        flex device-mapper-devel SDL libpciaccess libusb freetype freetype-devel gnu-free-* qemu-* virt-* \
        libvirt* vte* NetworkManager-bluetooth brlapi fuse-devel dejavu* gnu-efi* pesign shim \
        iscsi-initiator-utils grub2-tools zip nasm acpica-tools glibc-static zlib-static
    - name: download dietlibc
      run: curl -Ls https://www.fefe.de/dietlibc/dietlibc-0.34.tar.xz -O DOC/dietlibc-0.34.tar.xz
    - name: download grub
      run: curl -Ls https://ftp.gnu.org/gnu/grub/grub-2.04.tar.xz -O GRUB2/grub-2.04.tar.xz
    - name: download edk2
      run: curl -Ls https://codeload.github.com/tianocore/edk2/zip/edk2-stable201911 -O EDK2/edk2-edk2-stable201911.zip
    - name: download exfat
      run: curl -Ls https://codeload.github.com/relan/exfat/zip/v1.3.0 -O ExFAT/exfat-1.3.0.zip
    - name: download libfuse
      run: curl -Ls https://codeload.github.com/libfuse/libfuse/zip/fuse-2.9.9 -O ExFAT/libfuse-fuse-2.9.9.zip
    
    - name: exec permission
      run: chmod +x ./INSTALL/all_in_one.sh
    - name: build
      run: cd ./INSTALL/ && bash all_in_one.sh
