name: Ventoy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: exec permission
      run: chmod +x ./INSTALL/all_in_one.sh
    - name: build
      run: cd ./INSTALL/ && bash all_in_one.sh
